apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "my-demo-app"
  annotations:
    # This MUST match your repository's slug on GitHub
    # (e.g., abc/backstage)
    github.com/project-slug: Shahzaibali9519/backstage
    # This MUST match your GitHub username
    github.com/user: 'Shahzaibali9519'
spec:
  type: service
  owner: user:default/guest
  lifecycle: experimental
  dependsOn: 
    - "resource:my-demo-app-ec2"
